### ISSUE TITLE
ngx-translate v16

### ISSUE THREAD

**Issue by CodeAndWeb** [lephyrus/ngx-translate-messageformat-compiler#117]
I am Andreas Löw - and started maintaining @ngx-translate/core. 
I just published ngx-translate 16. With support for standalone-components and several other improvement. 
See https://ngx-translate.org/getting-started/migration-guide/

Can you please update the dependencies to that new release?

**Comment by lephyrus** [comment]
@CodeAndWeb Hi Andreas, I was subscribed to the "future of the library" topic, so I'm aware—thanks for stepping up! :100: I should get around to releasing a new version soon. And thanks for including this plugin in your new docs.

**Comment by Servonius** [comment]
any ETA on this?

**Comment by jarekcimoch** [comment]
It's quite a blocking issue to upgrade to latest ngx-translate when using this package :(

**Comment by Kbdq** [comment]
For those who can't wait for @lephyrus to do his job - add the following to package.json and it will work

for npm:
```
"overrides": {
  "ngx-translate-messageformat-compiler": {
    "@ngx-translate/core": "$@ngx-translate/core"
  }
}
```
for pnpm:
```
"pnpm": {
  "peerDependencyRules": {
    "allowedVersions": {
      "ngx-translate-messageformat-compiler>@ngx-translate/core": "^16"
    }
  }
}
```

**Comment by lephyrus** [comment]
Hi @Kbdq, thanks for your contribution, that should help folks that want to use v16 until I release an update.

Your comment isn't bad, but I want to point out a misunderstanding, one that is important (not for me, but for the Open Source community as a whole):

Maintaining this library is _NOT_ my job. I've created it 8 years ago because I needed it for myself. In the hope of providing a benefit to others, I've published and maintained it ever since, in my own time, for free. Nobody has to thank me for that, I like to do it! But you're not entitled to put pressure on me. This library is very small and so is my time investment, to be clear. But this is the story behind so much of the software we use, and some people give a lot of their time for nothing in return. We're all better off if we understand this.

So yeah, I will update it. When I get to it.

**Comment by Kbdq** [comment]
@lephyrus I'm sorry for anything which could lead you to conclusion that someone is putting pressure on you! It's definitely not me and (I hope) nobody else. I just saw that you've prepared pull request solving the issue two weeks ago but something hinder to finish and approve it. Nobode else can finish it anyway, so I meant exactly that as "you work", and just posted a way to force install current version for all the people who need to use your useful library.

**Comment by lephyrus** [comment]
@Kbdq No worries! And thanks for clarifying how you meant it, which is not how I took it. It's been a long year... :sweat_smile:
