### ISSUE TITLE
Since v6 not translating anymore

### ISSUE THREAD

**Issue by danielehrhardt** [lephyrus/ngx-translate-messageformat-compiler#92]
![image](https://user-images.githubusercontent.com/19570043/193146677-6130574a-940f-44cb-8bf6-c4e89317032c.png)

**Comment by lephyrus** [comment]
Hey! Since it seems that v6 is generally working (see [Example App](https://stackblitz.com/edit/ngx-translate-messageformat-compiler-example) for instance), you will need to supply much more information for anyone to be able to help you. Are you getting any errors when your app is building or at runtime? What version of the relevant libraries are you using? How did you upgrade, did you change anything else?

If you've figured it out in the meantime, feel free to close this issue.

**Comment by egalley** [comment]
Hey everybody,

Same problem here, in StackBliz example just add a date field, like this

"people": "{gender, select, male{He is} female{She is} other{They are}} {how} {birthday, date, long}."
 
and you will get an error in console.

This error is not thrown in production when using ngx-translate-core

   getTranslation(lang) {
        this.pending = true;
        const loadingTranslations = this.currentLoader.getTranslation(lang).pipe(shareReplay(1), take(1));
        this.loadingTranslations = loadingTranslations.pipe(map((res) => this.compiler.compileTranslations(res, lang)), shareReplay(1), take(1));
        this.loadingTranslations
            .subscribe({
            next: (res) => {
                this.translations[lang] = this.extend && this.translations[lang] ? { ...res, ...this.translations[lang] } : res;
                this.updateLangs();
                this.pending = false;
            },
            error: (err) => {
                this.pending = false; // THIS DOES NOT DISPLAY ERROR OF COMPILER
            }
        });
        return loadingTranslations;
    }

**Comment by lephyrus** [comment]
@egalley Your problem will be solved once #96 is merged (and released). In the meantime, the workaround is to pass `formatters: {}` as part of the config (see README). Here is your example working in StackBlitz: https://stackblitz.com/edit/ngx-translate-messageformat-compiler-example-sen5zx
